MojioSDK/Models/Mojio.swift
MojioSDK/Models/Trip.swift

Renaming TimePeriod to TripDuration

Adding ConnectedState to Mojio object per telematics contract

---

MojioSDK/Client/AuthClient.swift

MB-34: Added API method for resetting password
Added error value keys for forgot and reset password API's

MB-35: Added API method for forgot password request

---

MojioSDK/Client/RestClient.swift

NOTE: I left "select" in the SDK though it is not yet implemented on the API.

Remove $ from pagination query parameters, as per PT-131

---

MojioSDK/Client/AuthClient.swift
MojioSDK/Client/AuthViewController.xib
MojioSDK/Client/RestClient.swift
MojioSDK/Common/JsonSerializer.swift
MojioSDK/Env/KeychainManager.swift

Update to run calls RestClient (URLEncoded and JSON)
Updated calls to use AuthToken everywhere

Moved Register, Login, Verify Pin, and Resend Pin to SDK

---

MojioSDK/Models/NotificationsSettings.swift
MojioSDK/Models/Odometer.swift
MojioSDK/Models/Speed.swift
MojioSDK/Models/Vehicle.swift

Update Settings and Speed JSON transform

Added VIN update back to Vehicle JSON transform

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Client/RestClient.swift
MojioSDK/Models/Distance.swift
MojioSDK/Models/Geofence.swift
MojioSDK/Models/NotificationsSettings.swift

Added geofence endpoint and models

Adding geofence to SDK

---

MojioSDK/Models/Geofence.swift
MojioSDK/Models/WifiRadio.swift

Remove deprecated geofence enable field

Add field restrictions to wifiradio json transform

---

MojioSDK/Models/Vehicle.swift
MojioSDK/Models/VehicleMeasures.swift

JIRA: https://1mojio.atlassian.net/browse/MB-1818

move VehicleFuelVolume from VehicleMeasures to Vehicle

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Models/Acceleration.swift
MojioSDK/Models/DeviceMeasurement.swift

Base device measurement class.

Add base DeviceMeasurement class as a base for models in SDK

---

MojioSDK/Client/AuthClient.swift
MojioSDK/Client/RestClient.swift
Podfile.lock

Update SDK to use background dispatch queue by default and add method to change queue

Allow for custom dispatch queue for SDK responses

---

MojioSDK/Models/Activity Streams/Activity.swift
MojioSDK/Models/Activity Streams/RootActivity.swift

moved Origin entity to the root level (RootActivity) for fixing bug MB-2124 Random name is displayed on New Car Added notification on Notifications screen

fixing MB-2124

---

MojioSDK/Models/Activity Streams/Activity.swift

Key name from https://1mojio.atlassian.net/browse/PT-1149

Added ‘Content’ property to support SMS messages in activity list

---

MojioSDK/Client/AuthClient.swift
MojioSDK/Client/RestClient.swift
MojioSDK/Env/ClientEnvironment.swift
MojioSDK/Models/Activity Streams/Activity.swift
MojioSDK/Models/Activity Streams/RootActivity.swift
MojioSDK/Models/Location.swift
MojioSDK/Models/Odometer.swift
MojioSDK/Models/Result.swift
MojioSDK/Models/User.swift
MojioSDK/Models/Vehicle.swift
MojioSDKTests/StorageApiTests.swift

Replaced AnyObject with Any
Replaced NSDictionary entries with [String: Any]
Replaces NSArray entries with strong declarations
Improved code readability

Fixed RestClient runEncodeJSON method. Added more Swift 3.0 style

---

MojioSDK/Client/RestClient.swift

Force unwrap caused crash on device in some cases

Got rid from force unwrapping when parsing response dictionary in RestClient

---

MojioSDK/Client/RestClient.swift

Wrong url format :
"https://api.moj.io/v2/vehicles/16c5f88d-f72f-463b-8bcf-f6d8119d9505/diagnosticcodes//P0302/"
Correct format:
"https://api.moj.io/v2/vehicles/16c5f88d-f72f-463b-8bcf-f6d8119d9505/diagnosticcodes/P0302"
Source:
https://staging-api.moj.io/swagger/ui/index#/
PUT /v2/vehicles/{id}/diagnosticcodes/{code} Update details for a specific DTC code on a vehicle

*MB-2883 DTC is ignored after killing and re opening the app.

---

MojioSDK/Client/RestClient.swift
MojioSDK/Extensions/StringExt.swift

and to provide fixing issue MB-3892: "App indicates car as offline if device time is not correctly set".

Added argument "headers" to "completion" closure to be able to send headers data to a listener

---

MojioSDK/Client/Accounts/AuthClient.swift
MojioSDK/Client/Core/RestClient.swift
MojioSDK/Client/Pets/PetsClient.swift
MojioSDK/Env/ClientEnvironment.swift

Added Tracker endpoint
Minor fixes

Added Tracker endpoint

---

MojioSDK/Models/Core/Location.swift

Added class extension per work done in Pets

PHIOS-121: Location support for CLLocation

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Client/Pets/PetsClient.swift
MojioSDK/Models/Core/ActivitySettings.swift

PHIOS-257: Added ActivitySettings model

---

MojioSDK/Client/Accounts/AuthClient.swift
MojioSDK/Client/Accounts/WSAccountsClient.swift
MojioSDK/Client/Vehicles/WSVehiclesClient.swift
MojioSDK/Env/KeychainManager.swift

PHIOS-412 App is automatically switching to other account.
PHIOS-414 User is automatically logged out.

fixed issues:

---

MojioSDK/Models/Vehicles/VinDetails/Vin.swift
MojioSDKTests/Models/Vehicles/GeofenceRegionTests.swift
MojioSDKTests/Models/Vehicles/GeofenceTests.swift

Hotfix vin

---

MojioSDK/Models/Vehicles/VehicleActivitySettings.swift

Made Speed Threashold optional to fix parsing error

made speed threashhold optional

---

MojioSDK/Models/Vehicles/WifiRadio.swift

Appended support WifiRadio update.
!! Not tested, account with wifi support is needed

PHIOS-67 Wifi hotspot update

---

MojioSDK/Client/Accounts/AuthClient.swift

https://1mojio.atlassian.net/browse/PHIOS-541

PHIOS-541 'Unexpected error' is displayed when user disconnects the internet.

---

MojioSDK/Client/Accounts/AuthClient.swift

[PHIOS-844](https://1mojio.atlassian.net/browse/PHIOS-844)

[PHIOS-844]: changed error handling in deleting account

---

MojioSDK/Env/ClientEnvironment.swift

https://1mojio.atlassian.net/browse/PHIOS-1077

PHIOS-1077 [MoviStar]: "Error: The operation could not be complete" popup is displayed on "Complete Pet Profile" screen.

---

MojioSDK/Client/Vehicles/VehiclesClient.swift

We have to handle "tag" responses for bug (PHIOS-1019)

PHIOS-1019. Handling response for requests of tag

---

MojioSDK/Models/Core/Activity.swift

Updated ActivityLocationModel

---

MojioSDK/Client/Accounts/AuthViewController.swift

[PHIOS-1231: Xcode 10](https://1mojio.atlassian.net/browse/PHIOS-1231)
[PHIOS-1235: Swift 4.2](https://1mojio.atlassian.net/browse/PHIOS-1235)

[PHIOS-1231, PHIOS-1235] xcode 10 & Swift 4.2

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/PHIOS-1549
decode entity icon

Phios-1549: Icon entity

---

MojioSDK/Models/Core/Activity.swift

PHIOS-1958

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/PHIOS-1508

PHIOS-1508 [Telus]: Vehicle icon is not displayed on 'Entered' and 'Exited' geofence screen.

---

MojioSDK/Models/Vehicles/VehicleAppearanceStyle.swift

https://1mojio.atlassian.net/browse/PHIOS-2179

fixed issue PHIOS-2179 [TMCZ]: Changed Car style is not reflect on the iOS App after update from Android App.

---

MojioSDK/Client/Images/ImagesClient.swift

[PHIOS-2135](https://1mojio.atlassian.net/browse/PHIOS-2135)
Added generic method for uploading photos

PHIOS-2135 added generic method for uploading ImageModel type

---

MojioSDK/Models/Vehicles/Vehicle.swift
MojioSDK/Models/Vehicles/VehicleActivitySettings.swift

[PHIOS-477](https://1mojio.atlassian.net/browse/PHIOS-477)

[PHIOS-477]: Vehicle images

---

MojioSDK/Models/Vehicles/VehicleAppearance.swift

Reverts mojio/mojio-ios-sdk#223

Revert "PHIOS-2796 added Equatable extension for AppearanceImage"

---

MojioSDK/Models/Vehicles/Vehicle.swift
MojioSDK/Models/Vehicles/VehicleActivitySettings.swift

Reverts mojio/mojio-ios-sdk#184

Revert "[PHIOS-477]: Vehicle images"

---

MojioSDK/Client/Images/ImagesClient.swift

Platform appears to be ready now so OK to merge

PHIOS-2632: encrypt images

---

MojioSDK/Models/Vehicles/Mojio.swift

Appended "mainFirmware" field
https://1mojio.atlassian.net/browse/PHIOS-2626

PHIOS-2626 [DM-528][TMUS] Update device detail screen fields

---

MojioSDK.xcodeproj/project.pbxproj

https://1mojio.atlassian.net/browse/PHIOS-3138

Updated sdk to swift 4.2 standard - PHIOS-3138

---

MojioSDK.xcodeproj/project.pbxproj

https://1mojio.atlassian.net/browse/PHIOS-3138

Missed update for target Tests to swift 4.2 - PHIOS-3138

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Client/Core/RestClient.swift

https://1mojio.atlassian.net/browse/PHIOS-3138

Swift 5 compatibility updates - PHIOS-3138

---

Podfile
Podfile.lock

https://1mojio.atlassian.net/browse/PHIOS-3138

Point websocket pod to master

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Models/Pets/Device.swift
MojioSDK/Models/Pets/Light.swift
MojioSDK/Models/Pets/TemperatureAlarm.swift

- PHIOS-3170 [Pets][API Ready] Home screen status - connect temperature to API
- PHIOS-3176 [Pets][API Ready] Pet Online/Offline status - integrate with Platform [New implementation]
also added handling values "light, "msisdn" and "manufacturer" for "Device" entity

Implementation features:

---

MojioSDK/Models/Vehicles/VehicleAppearance.swift

https://1mojio.atlassian.net/browse/PHIOS-3411

PHIOS-3411 Missing Car Image Flow

---

MojioSDK/Models/Pets/PetDetails.swift

https://1mojio.atlassian.net/browse/PHIOS-3369

PHIOS-3369 add Neutered field

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/PHIOS-3308

Added new activity type to handle VehicleActor type

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/PHIOS-3553
Activities use a specific format and this pr should handle this format as well.

PHIOS-3553: parse activities' location 

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Models/Pets/Buzzer.swift
MojioSDK/Models/Pets/Device.swift

Added: lostMode, buzzer, skipEgress for DeviceUpdate support

Added fields to support egress functions for pet tracker controls

---

MojioSDK/Models/Pets/Buzzer.swift
MojioSDK/Models/Pets/Light.swift

https://1mojio.atlassian.net/browse/PHIOS-3364

Add support for Light and Buzzer in sdk

---

MojioSDK/Models/Pets/Geofence.swift

https://1mojio.atlassian.net/browse/PHIOS-4209

PHIOS-4209 [SyncUP PETS]: 'Enter & Exit Notifications' toggle remains  'ON'.

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/PHIOS-4220
⁉️ What does this PR do?
* Appended new type of time line event - "Service Schedule"

PHIOS-4220 [Assurant] Server Error when trying to load timeline

---

MojioSDK/Models/Pets/Device.swift

Added BLE-related properties

---

MojioSDK/Models/Pets/Device.swift

Needed for https://1mojio.atlassian.net/browse/TPE-4293

Added BleName field to DeviceUpdate

---

MojioSDK/Models/Pets/ActivitySettings.swift

https://1mojio.atlassian.net/browse/TPE-3987 
Bohdan's PR

TPE-3987 PM-869: PETS - [iOS] - Low/High Temperature notification settings (remove "API integration coming soon" error message)

---

MojioSDK/Models/Pets/AssetDailySummary.swift

This pr adds distance property.

PHIOS-4046: add distance to AssetDailySummary

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Client/Pets/PetsClient.swift
Podfile.lock

- Update latest cocoa pods
- Fix return method

Fix return method

---

MojioSDK/Models/Core/Activity.swift

Related to:
https://1mojio.atlassian.net/browse/TDE-1677
* Changed decode of Activitty id field to decodeIfPresent

TDE-1677: Changed decode of Activitty id field to decodeIfPresent

---

MojioSDK/Models/Vehicles/VehicleActivitySettings.swift

Related to [PHIOS-4484](https://1mojio.atlassian.net/browse/PHIOS-4484)
⁉️ What does this PR do?
Changed fields of VehicleActivitySettings to optional.

PHIOS-4484: changed fields of VehicleActivitySettings to optional

---

MojioSDK/Models/Core/Activity.swift

https://1mojio.atlassian.net/browse/TDE-1666
https://1mojio.atlassian.net/browse/TDE-1881
Added missing Seatbelt type. Renamed activity types (different from platform timeline type) for oil

[TDE-1666][TDE-1881] Added and corrected activity types

---

MojioSDK/Models/Vehicles/Units.swift

Related to [TDE-1599](https://1mojio.atlassian.net/browse/TDE-1599)
⁉️ What does this PR do?
Implemented `Equatable` protocol for `RiskSeveriry` ennumeration.

TDE-1599: implemented `Equatable` protocol for `RiskSeverity`.

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Client/Accounts/AuthViewController.swift
MojioSDK/Client/Accounts/AuthViewController.xib

https://1mojio.atlassian.net/browse/PHIOS-4536

[PHIOS-4536] Refactored UIWebview (deprecated) to WKWebview

---

MojioSDK/Models/Vehicles/EngineOil.swift

Related to:
https://1mojio.atlassian.net/browse/TDE-2220
* Fixed wrong OilLevelWarning veryLow case rawValue;

Fixed wrong OilLevelWarning veryLow case rawValue

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Models/Core/Activity.swift
MojioSDK/Models/Vehicles/TirePressure.swift

Added support for TirePressure activity and model

[TirePressure][3.6.5] TirePressure support

---

MojioSDK/Models/Vehicles/TirePressure.swift

[TirePressure][SDK] Fixed build errors

---

MojioSDK/Models/Vehicles/Vehicle.swift

Add support for TirePressure from endpoint v2/vehicles

[TirePressure][MDI] v2-vehicles-support

---

MojioSDK/Models/Vehicles/TirePressure.swift

Added model for interpreting TirePressure levels

Added model for interpreting TirePressure levels

---

MojioSDK.xcodeproj/project.pbxproj
MojioSDK/Models/Vehicles/PredictiveMaintenance.swift
MojioSDK/Models/Vehicles/Vehicle.swift
MojioSDKTests/Models/Vehicles/VehicleTests.swift

Added Warning State model;
Added Predictive Maintenance model;
Added Predictive Maintenance field to the Vehicle object
Updated vehicle unit test

Predictive Maintenance:

---

MojioSDK/Models/Core/Activity.swift

Adds support to the Tire Pressure Object in Activity models.

Added support for Tire Pressure Object to Activity

---

MojioSDK/Client/Vehicles/VehiclesClient.swift

Related to:
https://1mojio.atlassian.net/browse/PHIOS-4879
* Speeding Violations parsing changes;

Speeding Violation parsing changes
